apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: collinskimutai72/mahkeja-backend
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: my-secret
