apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: collinskimutai72/mahkeja-frontend
          ports:
            - containerPort: 3001
          envFrom:
            - secretRef:
                name: my-secret
